[project]
name = "sweco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "matplotlib>=3.5.3",
    "notebook>=6.5.7",
    "pandas>=1.1.5",
    "plotly>=5.18.0",
    "scikit-learn>=1.0.2",
    "scipy>=1.7.3",
]
